// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth": {
            "get": {
                "description": "Проверяет, зарегистрирован ли пользователь по telegram_id. Если пользователь найден, возвращает его данные, иначе – сообщение об ошибке.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Проверка авторизации пользователя",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Уникальный идентификатор Telegram",
                        "name": "telegram_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Данные пользователя",
                        "schema": {
                            "$ref": "#/definitions/auth.RegisterInput"
                        }
                    },
                    "400": {
                        "description": "Ошибка telegram_id is required",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не найден",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Регистрация пользователя с помощью уникального telegram_id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Регистрация пользователя",
                "parameters": [
                    {
                        "description": "Данные пользователя для регистрации",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.RegisterInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешная регистрация",
                        "schema": {
                            "$ref": "#/definitions/response.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Ошибка валидации",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Пользователь уже зарегистрирован",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "507": {
                        "description": "Не удалось создать пользователя",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/meetings": {
            "post": {
                "description": "Создает новую встречу для команды. Доступно только для менеджеров.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "meetings"
                ],
                "summary": "Создание встречи",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Уникальный идентификатор Telegram",
                        "name": "telegram_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Данные встречи",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/meetings.CreateMeetingInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Информация о созданной встрече",
                        "schema": {
                            "$ref": "#/definitions/response.MeetingResponse"
                        }
                    },
                    "400": {
                        "description": "Ошибка валидации или некорректные данные",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не найден",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Доступ запрещен (не менеджер)",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Конфликт по времени и аудитории",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/meetings/available-slots": {
            "get": {
                "description": "Возвращает список доступных временных слотов для указанной аудитории на выбранную дату",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "meetings"
                ],
                "summary": "Получение доступных временных слотов",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Номер аудитории",
                        "name": "room",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Дата в формате YYYY-MM-DD",
                        "name": "date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список доступных временных слотов",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/meetings.TimeSlot"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Отсутствуют обязательные параметры или неверный формат",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка при получении данных",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/meetings/my": {
            "get": {
                "description": "Возвращает список всех встреч команды, к которой привязан пользователь",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "meetings"
                ],
                "summary": "Получение встреч команды",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Уникальный идентификатор Telegram",
                        "name": "telegram_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список встреч команды",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/response.MeetingResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Отсутствует telegram_id или у пользователя нет команды",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не найден",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка при получении встреч",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/meetings/{id}": {
            "delete": {
                "description": "Удаляет встречу из расписания команды. Доступно только для менеджеров.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "meetings"
                ],
                "summary": "Удаление встречи",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Уникальный идентификатор Telegram",
                        "name": "telegram_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID встречи",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Встреча успешно удалена",
                        "schema": {
                            "$ref": "#/definitions/response.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Отсутствует telegram_id или ID встречи",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не найден",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Доступ запрещен (не менеджер)",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Встреча не найдена",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка при удалении встречи",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tasks": {
            "post": {
                "description": "Creates a new task for a team or individual user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tasks"
                ],
                "summary": "Create a new task",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Telegram ID of the manager",
                        "name": "telegram_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Task information",
                        "name": "task",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tasks.TaskInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Задача успешно создана",
                        "schema": {
                            "$ref": "#/definitions/response.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "assigned_to обязателен для персональных задач",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не найден",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Только менеджер может создавать встречи",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка при создании задачи",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/team": {
            "put": {
                "description": "Обновляет название и описание команды. Доступно только для менеджеров.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "team"
                ],
                "summary": "Изменение информации о команде",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Уникальный идентификатор Telegram",
                        "name": "telegram_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Данные для обновления команды",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/team.CreateTeamInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Команда успешно обновлена",
                        "schema": {
                            "$ref": "#/definitions/response.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Ошибка валидации или отсутствует telegram_id",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не найден",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Доступ запрещен (не менеджер)",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Error:Отсутствует команда у пользователя Code:USER_HAS_NO_TEAM, Error:Команда не найдена Code:TEAM_NOT_FOUND",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorCodeResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка при обновлении команды",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Создает команду, если запрос исходит от пользователя с ролью manager.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "team"
                ],
                "summary": "Создание команды",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Уникальный идентификатор Telegram",
                        "name": "telegram_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Данные команды",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/team.CreateTeamInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Информация о созданной команде",
                        "schema": {
                            "$ref": "#/definitions/response.TeamResponse"
                        }
                    },
                    "400": {
                        "description": "Ошибка валидации или отсутствует telegram_id",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Доступ запрещен (не менеджер)",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка создания команды",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет команду и очищает связи со всеми участниками. Доступно только для владельца команды.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "team"
                ],
                "summary": "Удаление команды",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Уникальный идентификатор Telegram",
                        "name": "telegram_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Команда успешно удалена",
                        "schema": {
                            "$ref": "#/definitions/response.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Отсутствует telegram_id",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не найден",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Error: Только руководитель может удалить команду Code: ONLY_MANAGER_DELETE_TEAM, Error: Вы не являетесь владельцем команды Code: NOT_OWNER_OF_TEAM",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorCodeResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка при удалении команды",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/team/invite": {
            "get": {
                "description": "Возвращает ссылку для приглашения новых участников в команду. Доступно только для менеджеров.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "team"
                ],
                "summary": "Получение ссылки-приглашения",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Уникальный идентификатор Telegram",
                        "name": "telegram_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "URL ссылки-приглашения",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Отсутствует telegram_id",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не найден",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Доступ запрещен (не менеджер)",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Error:Отсутствует команда у пользователя Code:USER_HAS_NO_TEAM, Error:Команда не найдена Code:TEAM_NOT_FOUND",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorCodeResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка при создании/получении ссылки-приглашения",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/team/join": {
            "post": {
                "description": "Позволяет пользователю присоединиться к команде, используя пригласительный код.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "team"
                ],
                "summary": "Присоединение к команде",
                "parameters": [
                    {
                        "description": "Данные для присоединения к команде",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/team.InviteJoinRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешное присоединение к команде",
                        "schema": {
                            "$ref": "#/definitions/response.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Ошибка валидации",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Error: Команда не найдена CODE: INVITE_CODE_INVALID, Error: Команда не найдена. CODE: TEAM_NOT_FOUND, Error: Пользователь не найден. Зарегистрируйтесь через бота. CODE: USER_NOT_FOUND",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorCodeResponse"
                        }
                    },
                    "409": {
                        "description": "Вы уже присоединились к этой команде",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка при присоединении к команде",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/team/kick": {
            "get": {
                "description": "Позволяет менеджеру исключить участника из команды",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "team"
                ],
                "summary": "Исключить участника из команды",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Уникальный идентификатор Telegram",
                        "name": "telegram_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Уникальный идентификатор Telegram участника, который будет исключен",
                        "name": "kick_telegram_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Участник успешно исключен из команды",
                        "schema": {
                            "$ref": "#/definitions/response.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Отсутствует telegram_id или kick_telegram_id",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не найден",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Error: Только менеджер может исключить участника из команды. CODE: NOT_MANAGER, Error: Пользователь не находится в вашей команде, CODE: NOT_IN_TEAM",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка при попытке исключить участника из команды",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/team/leave": {
            "get": {
                "description": "Позволяет пользователю выйти из текущей команды",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "team"
                ],
                "summary": "Покинуть команду",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Уникальный идентификатор Telegram",
                        "name": "telegram_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Команда успешно покинута",
                        "schema": {
                            "$ref": "#/definitions/response.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Отсутствует telegram_id",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не найден",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Manager не может просто так покинуть команду",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Error: Отсутствует команда у пользователя Code: USER_HAS_NO_TEAM",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorCodeResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка при попытке покинуть команду",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/team/members": {
            "get": {
                "description": "Возвращает список всех участников команды, кроме текущего пользователя. Доступно только для менеджеров.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "team"
                ],
                "summary": "Получение списка участников команды",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Уникальный идентификатор Telegram",
                        "name": "telegram_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список участников команды",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/response.UserResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Отсутствует telegram_id или ошибка валидации",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не найден",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Доступ запрещен (не менеджер)",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Error:Отсутствует команда у пользователя Code:USER_HAS_NO_TEAM, Error:Команда не найдена Code:TEAM_NOT_FOUND",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorCodeResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка при получении участников команды",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/team/my": {
            "get": {
                "description": "Возвращает данные о команде, к которой принадлежит пользователь",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "team"
                ],
                "summary": "Получение информации о своей команде",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Уникальный идентификатор Telegram",
                        "name": "telegram_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Информация о команде",
                        "schema": {
                            "$ref": "#/definitions/response.TeamResponse"
                        }
                    },
                    "400": {
                        "description": "Отсутствует telegram_id",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не найден",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Error:Отсутствует команда у пользователя Сode:USER_HAS_NO_TEAM, Error: Команда не найдена Сode:TEAM_NOT_FOUND",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorCodeResponse"
                        }
                    }
                }
            }
        },
        "/user": {
            "get": {
                "description": "Получает информацию о пользователе по его Telegram ID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Получение информации о пользователе",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Telegram ID of the user",
                        "name": "telegram_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Информация о пользователе",
                        "schema": {
                            "$ref": "#/definitions/response.UserInfoResponse"
                        }
                    },
                    "400": {
                        "description": "Ошибка валидации или отсутствует telegram_id",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Пользователь не найден",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка создания команды",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.RegisterInput": {
            "type": "object",
            "required": [
                "name",
                "role",
                "telegram_id"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "role": {
                    "description": "\"manager\" или \"member\"",
                    "type": "string",
                    "enum": [
                        "manager",
                        "member"
                    ]
                },
                "telegram_id": {
                    "type": "string"
                }
            }
        },
        "meetings.CreateMeetingInput": {
            "type": "object",
            "required": [
                "date",
                "end_time",
                "meeting_type",
                "start_time",
                "title"
            ],
            "properties": {
                "date": {
                    "description": "Формат \"YYYY-MM-DD\"",
                    "type": "string"
                },
                "end_time": {
                    "description": "Формат \"HH:MM\"",
                    "type": "string"
                },
                "meeting_type": {
                    "description": "\"online\" или \"offline\"",
                    "type": "string"
                },
                "room": {
                    "description": "Обязательное для офлайн встреч",
                    "type": "string"
                },
                "start_time": {
                    "description": "Формат \"HH:MM\"",
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "meetings.TimeSlot": {
            "type": "object",
            "properties": {
                "end": {
                    "description": "Например, \"13:20\"",
                    "type": "string"
                },
                "start": {
                    "description": "Например, \"12:00\"",
                    "type": "string"
                }
            }
        },
        "response.ErrorCodeResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "response.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "response.MeetingResponse": {
            "type": "object",
            "properties": {
                "conference_link": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "integer"
                },
                "date": {
                    "type": "string"
                },
                "end_time": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "meeting_type": {
                    "type": "string"
                },
                "room": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "team_id": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "response.SuccessResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "response.TeamResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "invitelink": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "response.UserInfoResponse": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "team_name": {
                    "type": "string"
                }
            }
        },
        "response.UserResponse": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "telegram_id": {
                    "type": "string"
                }
            }
        },
        "tasks.TaskInput": {
            "type": "object",
            "required": [
                "deadline",
                "description",
                "is_team",
                "title"
            ],
            "properties": {
                "assigned_to": {
                    "type": "string"
                },
                "deadline": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "is_team": {
                    "type": "boolean"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "team.CreateTeamInput": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "team.InviteJoinRequest": {
            "type": "object",
            "required": [
                "invite_code",
                "telegram_id"
            ],
            "properties": {
                "invite_code": {
                    "type": "string"
                },
                "telegram_id": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Сервис для контроля задачами и встречами команды",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
